## First numpy

In [1]:
import numpy as np

In [2]:
import sklearn

In [3]:
myarr = np.array([[3, 6, 7, 23]], np.int32)

In [4]:
myarr[0,1]

np.int32(6)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1] = 23

In [8]:
myarr

array([[ 3, 23,  7, 23]], dtype=int32)

# Array convertion : Convertion from other python structure

In [9]:
listarray = np.array([[1,2,3] , [4,5,6], [7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

# intrinsic numpy array crteation objects

In [14]:
import numpy as np

In [15]:
zeros = np.zeros((3,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(3, 5)

In [19]:
zeros.size

15

In [20]:
rng = np.arange(10)

In [21]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
lspace = np.linspace(1,6,13)

In [23]:
lspace

array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
       3.08333333, 3.5       , 3.91666667, 4.33333333, 4.75      ,
       5.16666667, 5.58333333, 6.        ])

In [24]:
emp = np.empty((2,5))

In [25]:
emp

array([[nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
       3.08333333, 3.5       , 3.91666667, 4.33333333, 4.75      ,
       5.16666667, 5.58333333, 6.        ])

In [28]:
ide =np.identity(15)

In [29]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [30]:
ide.shape

(15, 15)

In [31]:
ide.size

225

In [32]:
ide.dtype

dtype('float64')

In [33]:
import numpy as np

In [34]:
arr = np.arange(99)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Numpy Axis

In [38]:
x = [[1,2,3] , [4,5,6] , [7,1,0]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [46]:
ar.ndim

2

In [47]:
arr.ndim

1

In [48]:
ar.size

9

In [49]:
ar.dtype

dtype('int64')

In [50]:
ar.shape

(3, 3)

In [51]:
ar.nbytes

72

In [52]:
one = np.array([1,2,3,4,5,6,7,8,9])

In [53]:
one.argmax()

np.int64(8)

In [54]:
one.argmin()

np.int64(0)

In [55]:
one.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [60]:
ar.argmax()

np.int64(6)

In [61]:
ar.argmin()

np.int64(8)

In [62]:
ar.argmax(axis=0)

array([2, 1, 1])

In [64]:
ar.argmax(axis=1)

array([2, 2, 0])

In [65]:
ar.argmin(axis=0)

array([0, 2, 2])

In [66]:
ar.argmin(axis=1)

array([0, 0, 2])

In [68]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [69]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [71]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [74]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
ar2 = np.array([[1, 4, 3], [4, 0, 6], [7, 6, 0]])

In [77]:
ar2

array([[1, 4, 3],
       [4, 0, 6],
       [7, 6, 0]])

In [78]:
ar+ar2

array([[ 2,  6,  6],
       [ 8,  5, 12],
       [14,  7,  0]])

In [79]:
[2,5] + [3,7]

[2, 5, 3, 7]

In [80]:
ar*ar2

array([[ 1,  8,  9],
       [16,  0, 36],
       [49,  6,  0]])

In [82]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [83]:
np.sqrt(ar2)

array([[1.        , 2.        , 1.73205081],
       [2.        , 0.        , 2.44948974],
       [2.64575131, 2.44948974, 0.        ]])

In [84]:
ar.sum()

np.int64(29)

In [85]:
ar.max()

np.int64(7)

In [86]:
ar.min()

np.int64(0)

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [90]:
np.where(ar<3)

(array([0, 0, 2, 2]), array([0, 1, 1, 2]))

In [91]:
type(np.where(ar>5))

tuple

In [93]:
np.count_nonzero(ar)

np.int64(8)

In [94]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [95]:
ar[1,2] = 0

In [98]:
np.nonzero(ar)

(array([0, 1]),)

In [99]:
import sys

In [100]:
py_ar = [2,7,44,36]

In [101]:
np_ar = np.array(py_ar)

In [102]:
sys.getsizeof(1) * len(py_ar)

112

In [103]:
np_ar.itemsize * np_ar.size

32

In [ ]:
np_ar.tolist()